### ISSUE TITLE
Regarding "Android 12-13" support

### ISSUE THREAD

**Issue by e-t-l** [chriswoope/resign-android-image#16]
Some clarifying questions (and this issue might serve as a helpful FAQ for users with similar inquiries):

1. The ReadMe describes Android 13 as "untested," but also mentions it "could also support resigning stock Android 12-13 OS images with very few modifications." Does this project currently (as of November 2022) work for Android 12 out of the box? If not, what kind of modifications are required?
2. As of October 2022, users on [this XDA thread](could also support resigning stock Android 12-13 OS images with very few modifications) could not find a way to make this script function on Pixel 7 with Android 13. Have you made any progress on compatibility with Pixel 7 or Android 13 since then?
3. If disabling OEM Unlocking is dangerous for this type of OS, are those dangers equally present in upstream GrapheneOS? Or do they do something differently to mitigate that risk?*

*And if disabling OEM unlocking is so dangerous, is it possible for this script to include an option to set the "Unlock OEM" option to permanently enabled (aka toggle is enabled, but option is grayed-out)?

**Comment by chriswoope** [comment]
1. Android 13-based current GrapheneOS works on Pixel 6 Pro, all other devices untested
2. It currently builds, but it's untested since I don't have the device
3. It's less risky with upstream GrapheneOS because they presumably test all releases on their own unlocked devices, while with this script you are probably directly running a newly resigned build on your locked production device without any testing beforehand

> *And if disabling OEM unlocking is so dangerous, is it possible for this script to include an option to set the "Unlock OEM" option to permanently enabled (aka toggle is enabled, but option is grayed-out)?

In theory yes, but it seems a lot of work for very little gain
